// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYlbf0UxpEvQTUT2Q5IawYDiJfpXemA8',
    appId: '1:1087099940858:web:12855d8e209bb7afd5fe43',
    messagingSenderId: '1087099940858',
    projectId: 'botanic-lifeline',
    authDomain: 'botanic-lifeline.firebaseapp.com',
    storageBucket: 'botanic-lifeline.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHjXAlMSe9BnZJ8pglMxorgYBFjUTidu8',
    appId: '1:1087099940858:android:86d6d04892738657d5fe43',
    messagingSenderId: '1087099940858',
    projectId: 'botanic-lifeline',
    storageBucket: 'botanic-lifeline.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekrEaI4iw2gYypSBinUilDE70Uegk4zU',
    appId: '1:1087099940858:ios:b1550eb27ea68727d5fe43',
    messagingSenderId: '1087099940858',
    projectId: 'botanic-lifeline',
    storageBucket: 'botanic-lifeline.appspot.com',
    iosClientId: '1087099940858-e7qku14nojt9udq831u33i0u4t10b4vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOnboarding',
  );
}
